import argparse
import csv
import json
from pathlib import Path


def parse_args():
    parser = argparse.ArgumentParser(
        description="Freeze hard BraTS cases for stage-1 experiments from batch validation metrics."
    )
    parser.add_argument(
        "--summary_csv",
        required=True,
        help="Path to summary_metrics.csv generated by batch_validate_postprocess.py.",
    )
    parser.add_argument(
        "--output_dir",
        default="",
        help="Directory to save hard_cases outputs. Defaults to the summary CSV parent directory.",
    )
    parser.add_argument(
        "--top_k",
        type=int,
        default=4,
        help="Always include the lowest post_mean_dice cases.",
    )
    parser.add_argument(
        "--et_threshold",
        type=float,
        default=0.20,
        help="Also include cases whose post_dice_ET is less than or equal to this threshold.",
    )
    parser.add_argument(
        "--tc_threshold",
        type=float,
        default=0.40,
        help="Also include cases whose post_dice_TC is less than or equal to this threshold.",
    )
    return parser.parse_args()


def safe_float(raw_value, default_value=0.0):
    if raw_value is None:
        return float(default_value)
    raw_value = str(raw_value).strip()
    if not raw_value:
        return float(default_value)
    return float(raw_value)


def load_rows(summary_csv):
    summary_csv = Path(summary_csv)
    with summary_csv.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = list(reader)
    if not rows:
        raise ValueError(f"No rows found in summary CSV: {summary_csv}")
    return rows


def build_case_entry(row):
    return {
        "case_id": row["case_id"],
        "post_mean_dice": safe_float(row.get("post_mean_dice")),
        "post_dice_ET": safe_float(row.get("post_dice_ET")),
        "post_dice_TC": safe_float(row.get("post_dice_TC")),
        "post_dice_WT": safe_float(row.get("post_dice_WT")),
        "raw_mean_dice": safe_float(row.get("raw_mean_dice")),
        "delta_mean_dice": safe_float(row.get("delta_mean_dice")),
        "output_dir": row.get("output_dir", ""),
        "html_path": row.get("html_path", ""),
        "reasons": [],
    }


def select_hard_cases(rows, top_k, et_threshold, tc_threshold):
    entries = [build_case_entry(row) for row in rows]
    sorted_entries = sorted(entries, key=lambda item: (item["post_mean_dice"], item["case_id"]))

    selected = {}

    for entry in sorted_entries[: max(int(top_k), 0)]:
        selected_entry = dict(entry)
        selected_entry["reasons"] = [f"top_{max(int(top_k), 0)}_lowest_post_mean_dice"]
        selected[selected_entry["case_id"]] = selected_entry

    for entry in sorted_entries:
        reasons = []
        if entry["post_dice_ET"] <= float(et_threshold):
            reasons.append(f"post_dice_ET<={float(et_threshold):.4f}")
        if entry["post_dice_TC"] <= float(tc_threshold):
            reasons.append(f"post_dice_TC<={float(tc_threshold):.4f}")
        if not reasons:
            continue
        if entry["case_id"] in selected:
            selected[entry["case_id"]]["reasons"].extend(reasons)
            continue
        selected_entry = dict(entry)
        selected_entry["reasons"] = reasons
        selected[selected_entry["case_id"]] = selected_entry

    final_entries = sorted(selected.values(), key=lambda item: (item["post_mean_dice"], item["case_id"]))
    for entry in final_entries:
        entry["reasons"] = sorted(set(entry["reasons"]))
    return final_entries


def write_outputs(output_dir, payload):
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    txt_path = output_dir / "hard_cases.txt"
    txt_path.write_text(
        "\n".join(item["case_id"] for item in payload["hard_cases"]) + "\n",
        encoding="utf-8",
    )

    json_path = output_dir / "hard_cases.json"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    md_path = output_dir / "hard_cases.md"
    lines = [
        "# Hard Cases",
        "",
        f"- Summary CSV: `{payload['summary_csv']}`",
        f"- Top K lowest post mean Dice: `{payload['top_k']}`",
        f"- ET threshold: `{payload['et_threshold']}`",
        f"- TC threshold: `{payload['tc_threshold']}`",
        "",
        "| Case | Post Mean Dice | Post Dice ET | Post Dice TC | Post Dice WT | Reasons |",
        "| --- | ---: | ---: | ---: | ---: | --- |",
    ]
    for item in payload["hard_cases"]:
        lines.append(
            f"| {item['case_id']} | "
            f"{item['post_mean_dice']:.4f} | "
            f"{item['post_dice_ET']:.4f} | "
            f"{item['post_dice_TC']:.4f} | "
            f"{item['post_dice_WT']:.4f} | "
            f"{', '.join(item['reasons'])} |"
        )
    lines.append("")
    md_path.write_text("\n".join(lines), encoding="utf-8")

    return txt_path, json_path, md_path


def main():
    args = parse_args()
    summary_csv = Path(args.summary_csv).resolve()
    output_dir = Path(args.output_dir).resolve() if args.output_dir else summary_csv.parent.resolve()

    rows = load_rows(summary_csv)
    hard_cases = select_hard_cases(
        rows=rows,
        top_k=args.top_k,
        et_threshold=args.et_threshold,
        tc_threshold=args.tc_threshold,
    )

    payload = {
        "summary_csv": str(summary_csv),
        "top_k": int(args.top_k),
        "et_threshold": float(args.et_threshold),
        "tc_threshold": float(args.tc_threshold),
        "num_selected": len(hard_cases),
        "hard_cases": hard_cases,
    }
    txt_path, json_path, md_path = write_outputs(output_dir, payload)

    print(json.dumps({
        "output_dir": str(output_dir),
        "hard_cases_txt": str(txt_path),
        "hard_cases_json": str(json_path),
        "hard_cases_md": str(md_path),
        "selected_case_ids": [item["case_id"] for item in hard_cases],
    }, indent=2))


if __name__ == "__main__":
    main()
